#ifndef  SENSOR_TWI_REG_H
#define SENSOR_TWI_REG_H


//Registros HTU21D
//#define HTU21D_ADDRESS 0x40
//#define HTU21D_HUMIDITY_NO_HOLD_MASTER_ADDRESS 0xF5
//#define HTU21D_TEMPERATURE_NO_HOLD_MASTER_ADDRESS 0xF3
//#define HTU21D_WRITE_USER_REGISTER 0xE6
//#define HTU21D_READ_USER_REGISTER 0xE7
//#define HTU21D_SOFT_RESET 0xFE



#endif